# Generated by Django 4.1 on 2022-11-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=512)),
                ("username", models.CharField(max_length=128)),
            ],
        ),
    ]
